about/urls.py
from django.urls import path
from about.views import AboutView

app_name = 'about'

urlpatterns = [
    path('', AboutView.as_view(), name='about'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('services/', include('services.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('about/', include('about.urls')),
    path('team/', include('team.urls')),
    path('contact/', include('contact.urls')),
]   

contact/urls.py
from django.urls import path
from contact.views import ContactView


app_name = 'contact'

urlpatterns = [
    path('', ContactView.as_view(), name='contact'),
]

home/urls.py
from django.urls import path
from home.views import HomeView


app_name = 'home'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    
]

services/urls.py
from django.urls import path
from services.views import ServiceView

app_name = 'service'

urlpatterns = [
    path('', ServiceView.as_view(), name='service'),

]

team/urls.py
from django.urls import path
from team.views import TeamView

app_name = 'team'

urlpatterns = [
    path('', TeamView.as_view(), name='team'),
]

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Azamat</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <img src="{% static 'img/header-bg.jpg' %}" alt="img">
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top"><img src="{% static 'img/navbar-logo.svg' %}" alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'service:service' %}">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'portfolio:portfolio'%}">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about:about'%}">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'team:team'%}">Team</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contact:contact'%}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>     
        {% block content %}


        {% endblock %}  
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 text-lg-start">Website &copy; Azamat</div>
                    <div class="col-lg-3 text-lg-start">My_projects <a href="https://github.com/">Github</a></div>
                    <div class="col-lg-3 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="https://twitter.com"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://uz.linkedin.com/"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-3 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="{% url 'service:service' %}">Xavfsizlik</a>
                        <a class="link-dark text-decoration-none" href="{% url 'service:service' %}">Foydalanish shartlari</a>
                    </div>
                </div>
            </div>
        </footer>
    
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>